### ISSUE TITLE
gitlab_project_mirror replaces existing mirror with each apply

### ISSUE THREAD

**Issue by tredfield** [gitlabhq/terraform-provider-gitlab#504]
### Terraform Version
Terraform v0.13.5
+ provider registry.terraform.io/gitlabhq/gitlab v3.2.0

### Affected Resource(s)
- gitlab_project_mirror

### Terraform Configuration Files
```hcl
resource "gitlab_project_mirror" "test_moving_mirror" {
  project                 = module.test_moving_old.project_id
  enabled                 = true
  url                     = "https://${var.mirror_user}:${var.mirror_token}@gitlab.com/######/###/poc/test-group/test-moving.git"
  only_protected_branches = false
  keep_divergent_refs     = false
}
```

### Debug Output
https://gist.github.com/tredfield/034de1667f23266e6fa563b211f7f306

### Panic Output
NA

### Expected Behavior
Once a gitlab_project_mirror is applied performing a plan or apply it should not change

### Actual Behavior
After performing an apply, each plan or apply after states the mirror must be replaced with statement "gitlab_project_mirror.test_moving_mirror must be replaced". See example

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # gitlab_project_mirror.test_moving_mirror must be replaced
-/+ resource "gitlab_project_mirror" "test_moving_mirror" {
        enabled                 = true
      ~ id                      = "22846482:259337" -> (known after apply)
        keep_divergent_refs     = false
      ~ mirror_id               = 259337 -> (known after apply)
        only_protected_branches = false
        project                 = "22846482"
      ~ url                     = (sensitive value)
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

The result is a new mirror is created in gitlab with each apply. The old mirror is disabled, creating a list of disabled mirrors.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
# initial add of mirror
1. `terraform apply`
2. `terraform apply`

# with no changes made to TF
3. `terraform plan`
4. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?
No

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
No

**Comment by hobti01** [comment]
I observe the same issue with 
```
$ terraform version
Terraform v0.12.29
+ provider.gitlab v3.3.0
```
When trying to set the username and password in the URL instead of using a static value.  With a static `url` I do not have this issue but it is not desirable to code the username and password :)

**Comment by marqzman** [comment]
I experience the same issue:

```
$ terraform --version
Terraform v0.13.4
+ provider registry.terraform.io/gitlabhq/gitlab v3.3.0
```

Even by using a static value for the URL I still experienced the issue.

**Comment by marqzman** [comment]
I updated to the latest version of terraform (v0.14.2). Still see that issue.

**Comment by RomanNess** [comment]
We just hit the same issue with provider v3.3.0.

This is definitely caused by the `url` field, since ignoring changes on this field in the `gitlab_project_mirror` mitigates the issue. 
```
lifecycle {
    ignore_changes = [
      url
    ]
}
```

Probably it has something to do with the fact that the `username` and `password` fields are always replaced with `******` by the GitLab-API (and this scrubbed `url` is persisted in the terraform state). 

Actually, the Terraform provider cannot detect changes to the `username` and `password` fields of the `url` with this information, unless it would store a hash of the url in the Terraform state.

**Comment by armsnyder** [comment]
@hobti01 Would you be able to provide either some steps to reproduce the problem with a plain URL, or run Terraform with `TF_LOG=TRACE` and upload the log output to a gist?

**Comment by armsnyder** [comment]
@marqzman  Would you be able to provide either some steps to reproduce the problem with a plain URL, or run Terraform with TF_LOG=TRACE and upload the log output to a gist?

**Comment by armsnyder** [comment]
@RomanNess I didn't follow your hash suggestion, but I think I've addressed the bug in #538 simply by not setting `url` on read. Thoughts?

**Comment by RomanNess** [comment]
@armsnyder It might be problematic in some scenario (including ours) that the full url including `username` and `password` is now persisted in the Terraform state. The `password` will typically be a personal access token with api access on a GitLab group. In our scenario only few people have access to this token and it is handed to the Terraform stack via environmental variable, while all devs have theoretical access to the Terraform remote state.

Not sure though, if other users have similar setups and whether they would also consider this a security risk.

**Comment by armsnyder** [comment]
@RomanNess Hmm I understand the desire to hash this information, but I think that might violate some Terraform design principles. 

https://www.terraform.io/docs/extend/best-practices/sensitive-state.html
> In light of these shortcomings, the encouraged solution at this time is to use a state backend that supports operations and encryption

Also https://www.terraform.io/docs/language/state/sensitive-data.html

I also see the AWS provider removed a bunch of state hashing recently, so that's discouraging https://github.com/hashicorp/terraform-provider-aws/issues/13406

There's an open issue in HashiCorp where this topic is being actively discussed if you're interested: https://github.com/hashicorp/terraform/issues/516

**Comment by RomanNess** [comment]
@armsnyder Thanks for the detailed response. I was not aware of this design principle. I would like to withdraw my previous suggestion. Following the design principles for Terraform providers is more important than our issues described above. 

In that case the solution looks good to me. That means, I built it earlier today and ran our stack with it and it was working as specified.

**Comment by ibacalu** [comment]
this issue is still happening in provider v3.6.0 and terraform v0.15.0

**Comment by roidelapluie** [comment]
https://github.com/gitlabhq/terraform-provider-gitlab/pull/632
